---
kind: pipeline
type: docker
name: dockerhub-build-trigger

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: call webhook
  pull: always
  image: bash:latest
  environment:
    ENDPOINT:
      from_secret: DOCKERHUB_ENDPOINT
  commands:
  - apk add --no-cache curl
  - curl -sO https://git.dotya.ml/${DRONE_REPO}/raw/branch/master/curl.it
  - bash ./curl.it $ENDPOINT

trigger:
  branch:
  - master
  event:
  - push
  - cron
