---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: hadolint
  pull: always
  image: hadolint/hadolint:v1.23.0-8-gb01c5a9-alpine
  commands:
  - hadolint --version
  - hadolint Dockerfile
  when:
    ref:
    - refs/heads/master
    - "refs/heads/feature-**"
    - "refs/pull/**"
    - "refs/tags/**"
    event:
      exclude: [cron]

- name: kaniko-build
  pull: always
  image: immawanderer/drone-kaniko:efd19c50
  settings:
    dockerfile: Dockerfile
    context: .
  when:
    ref:
    - "refs/heads/feature-**"
    - "refs/pull/**"
    - "refs/tags/**"
    event:
      exclude: [cron]

- name: kaniko-publish
  pull: always
  image: immawanderer/drone-kaniko:efd19c50
  settings:
    dockerfile: Dockerfile
    context: .
    tags:
    - latest
    - linux-amd64
    - ${DRONE_COMMIT_SHA:0:8}
    repo: immawanderer/alpine-android
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/heads/master
    event:
      exclude: [pull_request, tag]
trigger:
  event: [push, pull_request, cron, tag]

